# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Giles
tagline:          A sMAP Archiver
url:              http://gtfierro.github.com/giles
baseurl:          /

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/gtfierro/giles
